version: "2"

services:
  httpd:
    container_name: ksbrt-shortener-apache
    # image: httpd:2.4
    build: .
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - ../:/usr/local/apache2/cgi-bin:ro
      - ./apache-cgi.conf:/usr/local/apache2/conf/httpd.conf:ro